### ISSUE TITLE
Different datasets - data normalization or batch correction

### ISSUE THREAD

**Issue by dBenedek** [NourMarzouka/multiclassPairs#1]
Hello,

In case I use different datasets generated by different sequencing techniques and data preprocessing methods, is it recommended to do some sort of batch correction and/or data normalization?

Best,
Benedek Danko

**Comment by NourMarzouka** [comment]
Hello Benedek,
No specific recommendations. But if i were you i will not apply any batch correction. One of the advantages of this tool is to get the good rules that works across the different batches and datasets. So more heterozygous your training data the better classifier you get.

**Comment by NourMarzouka** [comment]
You can also check our paper, it talks about similar issues
https://academic.oup.com/bioinformatics/article/38/4/1022/6426072
