### ISSUE TITLE
RF prediction - class specificity of rules

### ISSUE THREAD

**Issue by dBenedek** [NourMarzouka/multiclassPairs#2]
Hello again,

Is there a way to get the class-specific rules (gene pairs) for the RF predictions?
Or in the case of RF, the selected rules are not class specific?
So for example after training and RF-based classifier, I get 212 rules for all classes. But is it possible to somehow link each rule to each class?

Cheers,
Benedek

**Comment by NourMarzouka** [comment]
You can see the class specific rules which were selected for training purpose. But i believe it is not straight forward after building the last classifier. The final RF model is a normal RF model and what applies on it similar to any RF.

The easiest way is to match the rules in the final RF classifier with the pre-training one-vs-rest rule lists. In this way you know each rule benifits which class. Some rules may be found in more than one class.
